apiVersion: v1
kind: Namespace
metadata:
  name: diff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diff-scan
  namespace: diff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diff-scan
  template:
    metadata:
      labels:
        app: diff-scan
    spec:
      containers:
        - name: diff-scan
          image: ghcr.io/dmitryoml/diffscan:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diff-scan
  namespace: diff
spec:
  selector:
    app: diff-scan
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diff-scan
  namespace: diff
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: diff.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diff-scan
                port:
                  number: 80
